// STATES
export const FOLLOW_REQUESTED_STATE = 'FOLLOW_REQUESTED';
export const NOT_A_FOLLOWER_STATE = 'NOT_A_FOLLOWER';
export const FOLLOWED_STATE = 'FOLLOWING';
export const UNFOLLOWED_STATE = 'UNFOLLOWED';
export const INITIAL_STATE = 'INITIAL_STATE';
export const EXTRAS_STATE = 'EXTRAS_STATE';
export const EDIT_STATE = 'EDIT_STATE';
export const REVIEW_STATE = 'REVIEW_STATE';
export const LOGIN_STATE = 'LOGIN_STATE';
export const REGISTER_STATE = 'REGISTER_STATE';
export const PASSWORD_STATE = 'PASSWORD_STATE';
export const NEW_ENTRY_MODAL_STATE = 'NEW_ENTRY_MODAL_STATE';
export const WORKS_STATE = "WORKS";
export const RELATION_MODAL_STATE = 'RELATION_MODAL_STATE';
export const PEOPLE_SEARCH_STATE = 'PEOPLE_SEARCH_STATE';
export const POST_VIEWER_MODAL_STATE = 'POST_VIEWER_MODAL_STATE';
export const PROJECT_MACRO_VIEW_STATE = 'PROJECT_MACRO_VIEW_STATE';
export const PROJECT_MICRO_VIEW_STATE = 'PROJECT_MICRO_VIEW_STATE';
export const PROJECT_SELECT_VIEW_STATE = 'PROJECT_SELECT_VIEW_STATE';
export const PROJECT_REARRANGE_STATE = 'PROJECT_REARRANGE_STATE';
export const PROJECT_CONTENT_ONLY_VIEW_STATE = 'PROJECT_CONTENT_ONLY_VIEW_STATE';
export const FRIEND_STATE = 'FRIEND_STATE';
export const EXTRA_CONTENT_STATE = 'EXTRA_CONTENT_STATE';

// ACTIONS
export const FOLLOW_ACTION = 'FOLLOW';
export const UNFOLLOW_ACTION = 'UNFOLLOW';
export const REMOVE_ACTION = 'REMOVE';
export const REQUEST_ACTION = 'REQUEST';
export const ACCEPT_ACTION = 'ACCEPT';
export const DECLINE_ACTION = 'DECLINE';

//OVERALL CONTENT TYPE
export const ALL = 'ALL';
export const DYNAMIC = 'DYNAMIC';
export const POST = 'POST';
export const PROJECT = 'PROJECT';
export const THREADS = 'THREADS';
export const PROJECT_EVENT = 'PROJECT_EVENT';
export const PUBLISHED = 'PUBLISHED';
export const PUBLISHED_EVENT = 'PUBLISHED_EVENT';
export const NEW_PROJECT = 'NEW PROJECT';
export const COLLAPSED = 'COLLAPSED';
export const EXPANDED = 'EXPANDED';
export const RECENT_POSTS = 'RECENT_POSTS';
export const FRIEND_POSTS = 'FRIEND_POSTS';
export const FRIENDS_FEED = 'FRIENDS_FEED';
export const EXTRAS_FEED = 'EXTRAS_FEED';
export const RESULTS = 'RESULTS';
export const SPOTLIGHT = 'SPOTLIGHT';
export const SPOTLIGHT_POST = 'SPOTLIGHT_POST';
export const SPOTLIGHT_PROJECT = 'SPOTLIGHT_PROJECT';
export const FOLLOWED_FEED = 'FOLLOWED_FEED';
export const CACHED = 'CACHED';
export const UNCACHED = 'UNCACHED';
export const USER = 'USER';

// POST TYPE
export const DISPLAY = 'DISPLAY';
export const COVER = 'COVER';
export const NONE = 'NONE';
export const SHORT = 'SHORT';
export const LONG = 'LONG';
export const NEW_LONG = 'NEW_LONG';
export const OLD_LONG = 'OLD_LONG';
export const EDIT = 'EDIT';
export const TITLE = 'TITLE';
export const OVERVIEW = 'OVERVIEW';


//POST PROGRESSION
export const SETBACK = 'SETBACK';
export const NEUTRAL = 'NEUTRAL';
export const MILESTONE = 'MILESTONE';

//PRIVACY
export const PUBLIC = 'PUBLIC';
export const PRIVATE = 'PRIVATE';
export const PERSONAL_PAGE = 'PERSONAL_PAGE';
export const PUBLIC_FEED = 'PUBLIC_FEED';

